### PR TITLE
Add codeblock escape helper

### PR DESCRIPTION
**Pull request by Fripe070**
It took more than [5 minutes](https://github.com/Breadcord/Breadcord/pull/218#discussion_r1555011840)

### CODE REVIEW

**Review by m31-galaxy — COMMENTED** [review]
Naming / docstring seems a little odd to me - aren't we escaping triple backticks within just a single code block? "Escape codeblocks" seems rather confusing to me.

**Comment by Fripe070** [comment]
It will escape all codeblock "denominators" (triple backticks) inside the text

**Comment by m31-galaxy** [comment]
How about a `make_codeblock` helper function which does the wrapping with triple backticks for you as well?

(Since I don't think this function would ever be called outside of creating a codeblock)

**Comment by Fripe070** [comment]
I guess that could work. Something like this? 
```python
def make_codeblock(code: str, langauge: str | None = None):
    ...
```

**Comment by m31-galaxy** [comment]
Plus an `escape_backticks` argument (invisible characters could screw with copy-paste which may be undesirable) and you're golden!

**Review by m31-galaxy — APPROVED** [review]

**Pull request merged**
