### PR TITLE
Run breadcord action

### PR DESCRIPTION
**Pull request by Fripe070**
### Checklist

- [ ] I have planned and discussed this feature with other contributors.
- [x] I have run basic tests on my code to ensure it is functional.
- [x] I have thoroughly tested my code with various states, contexts and edge cases.
- [x] I have searched for a similar pull request in this repository and didn't find anything relevant.

### Summary
Adds an action to run breadcord both with and without the TUI to ensure that it still runs with the latest changes. This should hopefully stop mistakes like that fixed in #150 from making it to main.

### Issues
(No related issues)

### Extra information
This requires a `BOT_TOKEN` secret to be set in the repo.

### CODE REVIEW

**Comment by m31-galaxy** [comment]
This sort of CI/Actions work is way beyond my ability, so I don't know if my code review will be worth much - I'll just have to trust your judgement on this. However, this is a welcome change - I can see this being expanded to loading a simple module which e.g. sends a message to ensure that all works as intended.

**Comment by Fripe070** [comment]
Yeah. This would probably also integrate well with tests, where we could have some sort of testing module that uses as large of a portion of the codebase as possible.

**Comment by m31-galaxy** [comment]
I might be trying to run before we're walking, but is it possible to do this from e.g. pytest? I have no idea how Python testing frameworks work to be honest

**Comment by Sophon96** [comment]
> I might be trying to run before we're walking, but is it possible to do this from e.g. pytest? I have no idea how Python testing frameworks work to be honest

"this" is very ambiguous. pytest (and other testing frameworks) are largely focused on unit testing (so checking the behaviors of individual functions). This PR sets up a good foundation for adding a testing CI workflow in the future.

**Comment by Sophon96** [comment]
I'm not too sure how this could prevent stuff like that fixed in #150. Seems like that would be reserved to unit testing.

**Comment by Fripe070** [comment]
> I'm not too sure how this could prevent stuff like that fixed in #150. Seems like that would be reserved to unit testing.

This in combination with a test module that requires an external dependency would have failed, something that’d be much harder to check using normal unit tests

**Comment by Fripe070** [comment]
Ngl this is a bad idea idk what past me was thinking

**Pull request closed without merging**
