### PR TITLE
Allow passing specific modules to update

### PR DESCRIPTION
**Pull request by Fripe070**
### Checklist
- [ ] I have planned and discussed this feature with other contributors.
- [ ] I have run basic tests on my code to ensure it is functional.
- [ ] I have thoroughly tested my code with various states, contexts and edge cases.
- [x] I have searched for a similar pull request in this repository and didn't find anything relevant.

### Summary
Allows specifying which modules to update with the `update` command.
Syntax: `update module_id1 module_id2 module_id3`

### Issues
(No related issues)

### Extra information
(No extra information)

### CODE REVIEW

**Review by m31-galaxy — DISMISSED** [review]
You fly this ship

**Comment by Fripe070** [comment]
this ship is about to pull a subnautica

**Comment by m31-galaxy** [comment]
holy ship

**Comment by Fripe070** [comment]
This PR _should_ be done now, though I am unsure of its stability

**Review by m31-galaxy — APPROVED** [review]

**Comment by m31-galaxy** [comment]
ngl I was expecting you to merge this

**Pull request merged**
