### PR TITLE
Requirement install patch 2: Electric Boogaloo 

### PR DESCRIPTION
**Pull request by Fripe070**
Follow-up to #150. I am so done with this

### CODE REVIEW

**Comment by m31-galaxy** [comment]
Brief explanation please? I'm so lost in my own code and do not have the mental capacity to brain right now

**Comment by Fripe070** [comment]
> Brief explanation please? I'm so lost in my own code and do not have the mental capacity to brain right now

Error that it’s getting a Requirement object passed when it needs a string

**Comment by Sophon96** [comment]
lgtm, can confirm that this is a bug

`check_call` is getting a bunch of Requirement objects rather than their string representation, causes an error.

**Review by m31-galaxy — APPROVED** [review]
It's a new day and my brain isn't dead - now that I can actually comprehend this, LGTM

**Pull request merged**
