### PR TITLE
Log module requirement installation and make it async

### PR DESCRIPTION
**Pull request by Fripe070**
### Checklist

- [ ] I have planned and discussed this feature with other contributors.
- [x] I have run basic tests on my code to ensure it is functional.
- [ ] I have thoroughly tested my code with various states, contexts and edge cases.
- [x] I have searched for a similar pull request in this repository and didn't find anything relevant.

### Summary
Makes `Module.install_requirements()` run asynchronously, and shows the pip install output through the logger instead of directly through stdout and stderr. This allows you to view pip output in the log file.

### Extra information
I suspect that making the function async might allow multiple modules to install requirements simultaneously, though this might be a cause for race conditions? I have not tested this system with more than a single module at once.

### CODE REVIEW

**Comment by m31-galaxy** [comment]
Just tested - simultaneous pip installation is possible, however it crashes if both processes try to access the same package at the same time. This is in fact more risky, especially during first startup after installing multiple modules. One solution would honestly be to just use `uv` - it implements a lock system where the slower process will patiently wait for the lock to be released without erroring.

**Comment by Fripe070** [comment]
So, should we go ahead and require the use of UV, or ditch async installs?

**Comment by m31-galaxy** [comment]
uv is probably the nicer approach long-term, because having installs be blocking for the bot could become problematic in production - especially over slow networks and/or for big downloads.

**Comment by Fripe070** [comment]
Fully working async requirement installation has been decided to be handled in another PR. In its current state, this PR merely _allows_ it to be run async, it never actually is.

**Review by m31-galaxy — APPROVED** [review]

**Pull request merged**
