### PR TITLE
fix(settings_manager): use correct setting for determining whether to send ephemeral responses

### LINKED ISSUE #132: `settings_manager` built-in/core module does not correctly get the value of the `ephemeral` setting
### Checklist

- [x] I have been able to successfully and reliably reproduce the issue.
- [x] I confirm this issue is present as of the latest commit on the `main` branch.
- [x] I have searched for a similar issue in this repository and didn't find anything relevant.

### Description

When attempting to use any of the `/settings` commands and subcommands, the bot errors because the code for all of the commands attempts to retrieve the value of the `ephemeral` setting with an extra `setting` part in the path, i.e. the usage of `ephemeral=self.bot.settings.settings.ephemeral.value` instead of `ephemeral=self.bot.settings.ephemeral.value`.

### Reproduction

1. Use any `/settings` commands or subcommands

### Expected behaviour

The bot correctly determines whether to send the message as ephemeral or not and sets/gets/updates/whatevers the setting.

### Attachments

(No attachments)

### Extra information

(No extra information)

### PR DESCRIPTION
**Pull request by Sophon96**
### Checklist

- [x] I have run basic tests on my code to ensure it is functional.
- [x] I have thoroughly tested my code with various states, contexts and edge cases.
- [x] I have searched for a similar pull request in this repository and didn't find anything relevant.

### Summary

Replaces all incorrect occurrences of `self.bot.settings.settings.ephemeral.value` with `self.settings.ephemeral.value`.

### Issues

- Fixes #132 

### Extra information

(No extra information)

### CODE REVIEW

**Comment by Sophon96** [comment]
The lint is unfortunate but the lint errors don't apply to my code.

**Comment by m31-galaxy** [comment]
@Fripe070 LGTM, but I want a second opinion as the commands have worked for me before. Would you be willing to self-assign and:

1. Check that the fix works as expected
2. Consult git blame to find when I introduced the problem

If not, I'll deal with this soon™

**Review by Fripe070 — APPROVED** [review]
Tested it with both `/settings set` and `/settings get`, and it seems to function

**Comment by Sophon96** [comment]
b5529eed5ed4a5f81a1ac9776d2beddf27259ecf

**Comment by Sophon96** [comment]
Actually, I'm not sure when it was introduced, but it was probably broken by that commit.

**Comment by Sophon96** [comment]
Never mind, broken by 3e228dbaf4de3560faf0b0438ba138f0252e13a7 @ThatOtherAndrew

**Pull request merged**
